### ISSUE TITLE
Importing user onelogin_user_mappings

### ISSUE THREAD

**Issue by ghost** [onelogin/onelogin#13]
When trying to import user mappings as indicated in the `--help` message we encounter this error:

    ```
    Terraform Import!
    Collecting User Mappings from OneLogin...
    This will import 5 resources. Do you want to continue? (y/n): y
    2020/06/25 12:19:10 Initializing Terraform with 'terraform init'...
    2020/06/25 12:19:10 Importing resource 1
    2020/06/25 12:19:11 Problem executing terraform import[terraform import onelogin_user_mappings.xxx-24774 24774] exit status 1
    ```

I'm not sure if this is ready yet but I wanted to give some feedback :)

**Comment by dcaponi** [comment]
Try running the standalone `terraform import onelogin_user_mappings.xxx-24774 24774` and see if that reveals any clue. Usually this is a problem with your main.tf or you may not have sideloaded the branch `feature/user_mappings_resource` or there may be an auth issue.

**Comment by ghost** [comment]
I have not sideloaded the mentioned branch I assume that's the issue. Unfortunately we don't have time to test this now. So I assume you can close the issue and we'll get back to you when we try that out.

**Comment by dcaponi** [comment]
If you already cloned the provider repository and did `make sideload` the procedure is identical but on the `feature/user_mappings_resource` branch. We had to hold off on merging it because Hashicorp wants to keep the number of resources to a minimum during initial review, which we're still waiting on. The import tool is being developed independent of the provider which is why you see all those options in the `--help` section. 

I'll close the issue for now.

**Comment by TwSimoneRoselli** [comment]
Hi @dcaponi , 

are there any updates in regard of the merge to master? We can see that we still need to sideload the feature branch in order to make this work.

Thanks
